### ISSUE TITLE
setup profiles for 0.6mm nozzle

### ISSUE THREAD

**Issue by DomCCT** [Jacotheron/FlashForge-CreatorPro2-PS-Profile#6]
wondering how to setup PS for FFCP2 with a 0.6nozzle instead of 0.4.  Do I simply just create new profiles ( print and printer settings) in PS and adjust for 0.6nozzle and this will override the vendor file or do I need to make a separate vendor file with 0.6mm valves in it and reference within configuration of slicer? Basically asking if I setup  print profiles for 0.6mm, do I need to take an extra steps with the vendor file considering that it is initially setup with 0.4mm nozzle values. 

Thank you for providing this! really excited to push the Creator pro 2 to the next level.

**Comment by Jacotheron** [comment]
There are quite a few lines in the vendor file that should be updated for a 0.6mm nozzle. You can also simply change these in PS directly (and detach them from the vendor file - ultimately the same results). When detaching, you will find them under the "User Presets" and "Physical Printers" sections for the printer (and other places).

The main advantages of the vendor file are its simplicity to define a bunch of printers (each mode is defined as a separate printer) with common properties between them (otherwise you might have to detach each mode separately); and that it is stored as a single file (for distribution). So instruction here are for the vendor file (detaching can be done in PS using its interface to find the relevant properties).

I am listing the lines that probably needs changing (and their original values):

Line 18 "variants = 0.4" => 
Line 46 "external_perimeter_extrusion_width = 0.40"
Line 51 "extrusion_width = 0.48" => you can set this to whatever you want, but as a rule of thumb we use 1.2 * nozzle diameter (thus for 0.6 we would use 0.72).
Line 55 "first_layer_extrusion_width = 0.48"
Line 62 "infill_extrusion_width = 0.48"
Line 67 "max_print_speed = 60" => this may need changing based on your maximum extrusion rate.
Line 79 "perimeter_extrusion_width = 0.48"
Line 93 "solid_infill_extrusion_width = 0.48"
Line 98 "support_material_extrusion_width = 0.40"
Line 116 "top_infill_extrusion_width = 0.48"
Line 139 "max_print_speed = 60"
Line 144 and others "layer_height = 0.05" => from line 127 is the print settings based on layer height (quality); you might want to update a few of these with what your nozzle can do. Typically we tend to stay within 1/4 to 3/4 of nozzle diameter. You can then also update the names (just look at how it get linked to from others, see line 285)
Line 755 "max_layer_height = 0.30" => with larger nozzle you can do greater maximums
Line 756 "min_layer_height = 0.05" => with larger nozzle, you probably can't do this thin
Line 795 "max_layer_height = 0.3,0.3" => same as above
Line 796 "min_layer_height = 0.05,0.05" => same as above
The following needs to be changed for each "printer" (from line 785):
Line 799 "printer_variant = 0.4"
Line 800 "nozzle_diameter = 0.4,0.4"

If you also want to be able to use both the 0.4 and 0.6 options, things get a bit more difficult:

1. Add a variant to the line 18 (we will call this later).
2. Instead of modifying some sections, duplicate them and change its name (for example by specifying the 0.6 in the name - you can't have 2 sections with the same name). Note that adding code between will move the lines further down, but typically the properties mentioned are what you would change.

After the changes, be sure to test it out, and see if there are any issues.
4.
